[profile.default]
solc_version = "0.8.28"
evm_version = "cancun"
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

[profile.london]
solc_version = "0.8.28"
evm_version = "london"
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

etherscan_api_key = "${ETHERSCAN_API_KEY}"

[rpc_endpoints]
# Mainnets
ethereum = "${ETHEREUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
cronos = "${CRONOS_RPC_URL}"
bnb = "${BNB_RPC_URL}"
gnosis = "${GNOSIS_RPC_URL}"
unichain = "${UNICHAIN_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
sonic = "${SONIC_RPC_URL}"
manta = "${MANTA_RPC_URL}"
mint = "${MINT_RPC_URL}"
boba = "${BOBA_RPC_URL}"
zksync = "${ZKSYNC_RPC_URL}"
shape = "${SHAPE_RPC_URL}"
appchain = "${APPCHAIN_RPC_URL}"
worldchain = "${WORLDCHAIN_RPC_URL}"
redstone = "${REDSTONE_RPC_URL}"
flow = "${FLOW_RPC_URL}"
hyperevm = "${HYPEREVM_RPC_URL}"
metis = "${METIS_RPC_URL}"
polygon_zkevm = "${POLYGON_ZKEVM_RPC_URL}"
lisk = "${LISK_RPC_URL}"
sei = "${SEI_RPC_URL}"
perennial = "${PERENNIAL_RPC_URL}"
story = "${STORY_RPC_URL}"
gravity = "${GRAVITY_RPC_URL}"
soneium = "${SONEIUM_RPC_URL}"
swellchain = "${SWELLCHAIN_RPC_URL}"
sanko = "${SANKO_RPC_URL}"
ronin = "${RONIN_RPC_URL}"
abstract = "${ABSTRACT_RPC_URL}"
morph = "${MORPH_RPC_URL}"
hychain = "${HYCHAIN_RPC_URL}"
mantle = "${MANTLE_RPC_URL}"
somnia = "${SOMNIA_RPC_URL}"
superseed = "${SUPERSEED_RPC_URL}"
cyber = "${CYBER_RPC_URL}"
powerloom = "${POWERLOOM_RPC_URL}"
arena_z = "${ARENA_Z_RPC_URL}"
b3 = "${B3_RPC_URL}"
base = "${BASE_RPC_URL}"
plasma = "${PLASMA_RPC_URL}"
onchain_points = "${ONCHAIN_POINTS_RPC_URL}"
apechain = "${APECHAIN_RPC_URL}"
funki = "${FUNKI_RPC_URL}"
mode = "${MODE_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrum_nova = "${ARBITRUM_NOVA_RPC_URL}"
celo = "${CELO_RPC_URL}"
hemi = "${HEMI_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
gunz = "${GUNZ_RPC_URL}"
zircuit = "${ZIRCUIT_RPC_URL}"
superposition = "${SUPERPOSITION_RPC_URL}"
ink = "${INK_RPC_URL}"
linea = "${LINEA_RPC_URL}"
bob = "${BOB_RPC_URL}"
anime = "${ANIME_RPC_URL}"
apex = "${APEX_RPC_URL}"
boss = "${BOSS_RPC_URL}"
berachain = "${BERACHAIN_RPC_URL}"
blast = "${BLAST_RPC_URL}"
plume = "${PLUME_RPC_URL}"
taiko = "${TAIKO_RPC_URL}"
syndicate = "${SYNDICATE_RPC_URL}"
scroll = "${SCROLL_RPC_URL}"
zero = "${ZERO_RPC_URL}"
xai = "${XAI_RPC_URL}"
katana = "${KATANA_RPC_URL}"
forma = "${FORMA_RPC_URL}"
zora = "${ZORA_RPC_URL}"
corn = "${CORN_RPC_URL}"
lordchain = "${LORDCHAIN_RPC_URL}"
degen = "${DEGEN_RPC_URL}"
metacade = "${METACADE_RPC_URL}"
ancient8 = "${ANCIENT8_RPC_URL}"
rari = "${RARI_RPC_URL}"
stable = "${STABLE_RPC_URL}"
# Testnets
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
